### ISSUE TITLE
Background Image in CSS Rule Not Inverted Properly

### ISSUE THREAD

**Issue by tamar-dev** [tamar-dev/NegativeColorSwitcher#2]
### 📋 **Description:**
There is a bug where the **negative color filter** incorrectly applies to background images that are set via **CSS rules** rather than inline styles. This issue causes the background image to get inverted when it should remain in its original state, leading to an undesired visual effect.

### 🔄 **Steps to Reproduce:**
1. Go to the website: [JDN News](https://www.jdn.co.il/news/2251823/).
2. Inspect the **main image** on the page, which is set as a background using the following CSS rule:
    ```css
    .elementor-506 .elementor-element.elementor-element-18c46c4:not(.elementor-motion-effects-element-type-background), 
    .elementor-506 .elementor-element.elementor-element-18c46c4 > .elementor-motion-effects-container > .elementor-motion-effects-layer {
        background-image: url("https://www.jdn.co.il/wp-content/uploads/2024/07/WhatsApp-Image-2024-07-29-at-23.19.28.jpeg");
    }
    ```
3. Notice that the image gets incorrectly inverted along with the rest of the page's content.

### 💡 **Expected Behavior:**
The background image should **remain in its original state** and not be inverted, just like other images on the page, even when the negative color filter is applied.

### 🔍 **Potential Solution:**
Consider using a **MutationObserver** to detect and handle background images set via CSS rules, and ensure they are excluded from the inversion filter, keeping them in their original state.

### 📝 **Additional Information:**
- This issue can be particularly noticeable on sites where background images are commonly set through external stylesheets.
- Ensure that any fix does not impact performance, especially on sites with many images or complex styles.
